name: img2pc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - gdal
  - pdal
  - python-pdal
  - pip
  - pip:
      - open3d
      - geopandas
      - rasterio
      - shapely
      - pandas
      - numpy
      - laspy
      - lazrs
      - ipykernel
      - torch
      - torchvision
      - matplotlib
      - seaborn
