name: img2pc
channels:
  - open3d-admin
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - geopandas
  - rasterio
  - shapely
  - pandas
  - numpy
  - laspy
  - open3d
  - python-pdal
  - gdal
  - ipykernel

  - pip:
      - pdal==3.2.2
#prefix: C:\Users\zech011\miniconda3\envs\img2pc
