name: img2pc
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=2.116
  - blas-devel=3.9.0
  - blosc=1.21.3
  - boost-cpp=1.78.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - ceres-solver=2.1.0
  - cfitsio=4.2.0
  - curl=8.0.1
  - draco=1.5.6
  - eigen=3.4.0
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - freexl=1.0.6
  - gdal=3.6.4
  - geos=3.11.2
  - geotiff=1.7.1
  - gettext=0.21.1
  - gflags=2.2.2
  - glog=0.6.0
  - hdf4=4.2.15
  - hdf5=1.14.0
  - icu=72.1
  - intel-openmp=2023.1.0
  - kealib=1.5.0
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.0.1
  - libdeflate=1.18
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgdal=3.6.4
  - libglib=2.76.2
  - libhwloc=2.9.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnetcdf=4.9.2
  - libpng=1.6.39
  - libpq=15.2
  - librttopo=1.1.0
  - libspatialite=5.0.1
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libwebp-base=1.3.0
  - libxml2=2.10.4
  - libzip=1.9.2
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - msys2-conda-epoch=20160418
  - nitro=2.7.dev6
  - numpy=1.24.3
  - openjpeg=2.5.0
  - openssl=3.1.0
  - pcre2=10.40
  - pip=23.1.1
  - pixman=0.40.0
  - poppler=23.04.0
  - poppler-data=0.4.12
  - postgresql=15.2
  - proj=9.2.0
  - pthreads-win32=2.9.1
  - python=3.8.16
  - python-pdal=3.2.3
  - python_abi=3.8
  - setuptools=67.7.1
  - snappy=1.1.10
  - sqlite=3.40.0
  - suitesparse=5.4.0
  - tbb=2021.9.0
  - tiledb=2.13.2
  - tk=8.6.12
  - ucrt=10.0.22621.0
  - vc=14.3
  - vs2015_runtime=14.34.31931
  - wheel=0.40.0
  - xerces-c=3.2.4
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - absl-py==1.4.0
      - affine==2.4.0
      - asttokens==2.2.1
      - attrs==23.1.0
      - backcall==0.2.0
      - cachetools==5.3.0
      - certifi==2022.12.7
      - charset-normalizer==3.1.0
      - click==8.1.3
      - click-plugins==1.1.1
      - cligj==0.7.2
      - colorama==0.4.6
      - comm==0.1.3
      - configargparse==1.5.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - dash==2.9.3
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - debugpy==1.6.7
      - decorator==5.1.1
      - executing==1.2.0
      - fastjsonschema==2.16.3
      - filelock==3.12.0
      - fiona==1.9.3
      - flask==2.2.3
      - fonttools==4.39.3
      - geopandas==0.12.2
      - google-auth==2.17.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.54.0
      - idna==3.4
      - importlib-metadata==6.6.0
      - importlib-resources==5.12.0
      - ipykernel==6.22.0
      - ipython==8.12.0
      - ipywidgets==8.0.6
      - itsdangerous==2.1.2
      - jedi==0.18.2
      - jinja2==3.1.2
      - jsonschema==4.17.3
      - jupyter-client==8.2.0
      - jupyter-core==5.3.0
      - jupyterlab-widgets==3.0.7
      - kiwisolver==1.4.4
      - laspy==2.4.1
      - lazrs==0.5.0
      - markdown==3.4.3
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mpmath==1.3.0
      - munch==2.5.0
      - nbformat==5.7.0
      - nest-asyncio==1.5.6
      - networkx==3.1
      - oauthlib==3.2.2
      - open3d==0.17.0
      - packaging==23.1
      - pandas==2.0.0
      - parso==0.8.3
      - pdal==3.2.3
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.2.0
      - plotly==5.14.1
      - prompt-toolkit==3.0.38
      - protobuf==4.22.3
      - psutil==5.9.5
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pygments==2.15.1
      - pyparsing==3.0.9
      - pyproj==3.5.0
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pywin32==306
      - pyzmq==25.0.2
      - rasterio==1.3.6
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - seaborn==0.12.2
      - shapely==2.0.1
      - six==1.16.0
      - snuggs==1.4.7
      - stack-data==0.6.2
      - sympy==1.11.1
      - tenacity==8.2.2
      - tensorboard==2.12.2
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - torch==2.0.0
      - torch-tb-profiler==0.4.1
      - torchaudio==2.0.1
      - torchvision==0.15.1
      - tornado==6.3.1
      - traitlets==5.9.0
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - urllib3==1.26.15
      - wcwidth==0.2.6
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.7
      - zipp==3.15.0
