name: img2pc
channels:
  - open3d-admin
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - geopandas=0.12.2
  - rasterio=1.3.4
  - shapely=2.0.1
  - pandas=1.5.2
  - numpy=1.23.5
  - laspy=2.3.0
  - open3d=0.11.2
  - python-pdal=3.2.2
  - gdal=3.6.2
  - ipykernel
  - pip

  - pip:
      - pdal==3.2.2
